
CREATE TABLE CATEGORY (
       BOARDTYPE NUMBER PRIMARY KEY,
       BOARDNAME VARCHAR2(300) NOT NULL
);

INSERT INTO CATEGORY VALUES(1, '일반게시판');
INSERT INTO CATEGORY VALUES(2, '사진게시판');

CREATE TABLE BOARD (
      BNO NUMBER PRIMARY KEY,
      BTYPE NUMBER NOT NULL,
      BTITLE VARCHAR2(500) NOT NULL,
      BCONTENT VARCHAR2(3000) NOT NULL,
      BWRITER VARCHAR2(15) NOT NULL,
      BCOUNT NUMBER DEFAULT 0,
      BOARDFILE VARCHAR2(600),
      BDATE DATE DEFAULT SYSDATE,
      STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
      CONSTRAINT FK_BTYPE FOREIGN KEY(BTYPE) REFERENCES CATEGORY(BOARDTYPE),
      CONSTRAINT FK_BWRITER FOREIGN KEY(BWRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL
);


CREATE TABLE BOARD_COMMENT (
      CNO NUMBER PRIMARY KEY,
      BNO NUMBER NOT NULL,
      CCONTENT VARCHAR2(2000) NOT NULL,
      CWRITER VARCHAR2(15) NOT NULL,
      CDATE DATE DEFAULT SYSDATE,
      REF_CNO NUMBER,
      CLEVEL NUMBER,
      CONSTRAINT FK_CWRITER FOREIGN KEY(CWRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL,
      CONSTRAINT FK_REF_CNO FOREIGN KEY(REF_CNO) REFERENCES BOARD_COMMENT(CNO) ON DELETE CASCADE
);

----- 시퀀스 작성 -----

CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE OR REPLACE PROCEDURE TEST_BOARD_DATA AS
BEGIN 
 FOR CNT IN 1..250 LOOP
    INSERT INTO BOARD VALUES (SEQ_BNO.NEXTVAL, 1, 'TEST SAMPLE ' || SEQ_BNO.CURRVAL, 'TEST SAMPLE 데이터입니다. ' || SEQ_BNO.CURRVAL, 'admin', DEFAULT, null, TO_DATE('19/01/01')+SEQ_BNO.CURRVAL, DEFAULT);
 END LOOP;
 COMMIT;
END;
/

EXEC TEST_BOARD_DATA;

COMMIT;

SELECT * FROM BOARD;

-- 각각의 게시글 순번 매기기 
SELECT ROWNUM RN , B.* 
FROM(SELECT * FROM BOARD 
WHERE BTYPE = 1 
AND STATUS = 'Y'
ORDER BY BNO DESC) B;

-- 특정 갯수 뽑아내기 
SELECT ROWNUM RN , B.* 
FROM(SELECT * FROM BOARD 
WHERE BTYPE = 1 
AND STATUS = 'Y'
ORDER BY BNO DESC) B
WHERE ROWNUM < 11;

-- 완전체
SELECT BO.*, (SELECT USERNAME FROM MEMBER 
				WHERE USERID = BO.BWRITER) "USERNAME" 
			 FROM (SELECT ROWNUM RN , B.* 
    				FROM(SELECT * FROM BOARD 
        				WHERE BTYPE = 1 AND STATUS = 'Y' 
        				ORDER BY BNO DESC) B 
   	     			WHERE ROWNUM < 31) BO 
				WHERE RN > 20;
                
                
select * from board;




